### ISSUE TITLE
Listing - Improve the state "no game available for the search"

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#86] opened 2022-03-14 13:40 UTC
https://swissgames.garden/?genres[]=adventure&states[]=development
https://projects.invisionapp.com/share/ZRUVZ9XXHQV#/screens/399321553
<img width="1792" alt="Screenshot 2022-03-14 at 14 42 22" src="https://user-images.githubusercontent.com/27284929/158184281-7893f76a-3395-40d7-8450-cac0d0d27b1a.png">

**Comment by tonifisler** [comment] 2022-03-14 23:08
duplicate of #28

**Closed by tonifisler** 2022-03-14 23:08 UTC
