### ISSUE TITLE
Game detail - Gif picture doesn't display in front

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#42] opened 2020-11-07 10:13 UTC
https://staging-api-gos.museebolo.ch/node/294/edit?destination=/admin/content/games%3Fstatus%3DAll%26field_completeness_value%3D7%26title%3D%26langcode%3DAll%26uuid%3D%26field_genres_target_id%3D%26field_studios_target_id%3D%26field_releases_state%3DAll%26field_releases_date_value%3D

<img width="1248" alt="Capture d’écran 2020-11-07 à 11 12 19" src="https://user-images.githubusercontent.com/27284929/98438399-2deee880-20ea-11eb-9335-0068effbbdf4.png">

**Comment by tonifisler** [comment] 2020-11-08 23:58
Duplicate of #29

**Closed** 2022-09-10 15:24 UTC
Labels: bug
